version: '3'

services:

  app:
    build: .
    image: 4info/docker-swarm-tutorial

  main:
    image: 4info/docker-swarm-tutorial
    ports:
        - 8090:8080
    deploy:
        replicas: 3
        
  
        
    
    
