version: '2'

services:

  app:
    build: .
    image: 4info/docker-swarm-tutorial

  staging-dep:
    image: 4info/docker-swarm-tutorial
    ports:
        - 8090:8080
        
  staging-tests:
    image: maven:3.2-jdk-8
    volumes:
      - .:/usr/src/mymaven
    working_dir: /usr/src/mymaven
    environment:
      - HOST_IP=staging-dep:8080
      - server.port=8090
      - server.host=http://localhost
    network_mode: host
    command: mvn test 

        
    
    
